version: 1.0.{build}
image:
- Ubuntu2004
- Visual Studio 2019
build_script:
- ps: $STATUS = 0
- ps: $PATHS = (((Get-ChildItem -Recurse 'CMakeLists.txt').FullName).replace('CMakeLists.txt', ''))
- ps: >-
    foreach ($MY_PATH in $PATHS)
    {
      ./building.ps1 $MY_PATH || STATUS = 1
    }
- ps: exit $STATUS
notifications:
- provider: Email
  to:
  - '{{commitAuthorEmail}}'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true