version: 1.0.{build}
image:
- Ubuntu2004
- Visual Studio 2019
build_script:
- ps: ./building.ps1
notifications:
- provider: Email
  to:
  - '{{commitAuthorEmail}}'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true