version: 1.0.{build}
image:
- Ubuntu2004
- Visual Studio 2019
build_script:
- pwsh: $STATUS = 0
- pwsh: ./building.ps1 || ($STATUS = 1)
- pwsh: 7z a build.zip "build"
- pwsh: Push-AppveyorArtifact build.zip
- pwsh: exit $STATUS
artifacts:
- path: build.zip
  name: build
notifications:
- provider: Email
  to:
  - '{{commitAuthorEmail}}'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true