name: CMake

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  find_all_tasks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: find
      run: |
        ALL_TASKS=$(find . -name "CMakeLists.txt" | sed 's/CMakeLists.txt//g')
        echo "ALL_TASKS=$ALL_TASKS" >> $GITHUB_ENV

  check_tasks:
    needs: find_all_tasks
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        tasks: [ $ALL_TASKS ]

    steps:
    - uses: actions/checkout@v3

    - name: Configure
      run: cmake -B ./${{ matrix.tasks }}/build -S ./${{ matrix.tasks }}

    - name: Build
      run: cmake --build ./${{ matrix.tasks }}/build