name: CMake

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  check_tasks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        IFS=$'\n'
        for tasks in $(find . -name "CMakeLists.txt" | sed 's/CMakeLists.txt//g')
        do
          cmake -B ./${tasks}/build -S ./${tasks};
          cmake --build ./${tasks}/build
          echo
        done
        unset IFS